version: '3.8'
services:
  backend-flask:
    environment:
      FRONTEND_URL: '*'
      BACKEND_URL: '*'
      AWS_ACCESS_KEY_ID: AKIAW3MEEWI6L6SJUYON
      # AWS_SECRET_ACCESS_KEY: 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
      # AWS_DEFAULT_REGION: ca-central-1
    build: ./backend-flask
    ports:
      - '4567:4567'
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: http://127.0.0.1:4567
    build: ./frontend-react-js
    ports:
      - '3000:3000'
    volumes:
      - ./frontend-react-js:/frontend-react-js
  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
networks:
  internal-network:
    driver: bridge
    name: cruddur
volumes:
  db:
    driver: local